### ISSUE TITLE
Run Trimmer Error

### ISSUE THREAD

**Issue by gdtms247** [Ozymandyaz/sonarr-episode-trimmer#1]
I've had Sonarr with the episode trimmer running for years without major issues but recently noticed the episodes weren't getting deleted and in the logs I noticed this when testing the custom script. Anyone run into similar of have suggestions? Thanks!!

2024-01-25 13:31:25.2|Debug|CustomScript|Executing external script: /config/CustomScripts/run-trimmer.sh
2024-01-25 13:31:25.2|Debug|run-trimmer.sh|Starting /config/CustomScripts/run-trimmer.sh 
2024-01-25 13:31:25.4|Debug|Api|[GET] /api/series?apikey=(removed) 404.NotFound (0 ms)
2024-01-25 13:31:25.4|Debug|run-trimmer.sh|ERROR    404 Not Found
2024-01-25 13:31:25.4|Debug|run-trimmer.sh|ERROR    b''
2024-01-25 13:31:25.4|Error|run-trimmer.sh|Traceback (most recent call last):
2024-01-25 13:31:25.4|Error|run-trimmer.sh|  File "/config/CustomScripts/sonarr-episode-trimmer.py", line 132, in <module>
2024-01-25 13:31:25.4|Error|run-trimmer.sh|    series = api_request('series')
2024-01-25 13:31:25.4|Error|run-trimmer.sh|             ^^^^^^^^^^^^^^^^^^^^^
2024-01-25 13:31:25.4|Error|run-trimmer.sh|  File "/config/CustomScripts/sonarr-episode-trimmer.py", line 47, in api_request
2024-01-25 13:31:25.4|Error|run-trimmer.sh|    return json.loads(resp_body)
2024-01-25 13:31:25.4|Error|run-trimmer.sh|           ^^^^^^^^^^^^^^^^^^^^^
2024-01-25 13:31:25.4|Error|run-trimmer.sh|  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
2024-01-25 13:31:25.4|Error|run-trimmer.sh|    return _default_decoder.decode(s)
2024-01-25 13:31:25.4|Error|run-trimmer.sh|           ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-25 13:31:25.4|Error|run-trimmer.sh|  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
2024-01-25 13:31:25.4|Error|run-trimmer.sh|    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-01-25 13:31:25.4|Error|run-trimmer.sh|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-25 13:31:25.4|Error|run-trimmer.sh|  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
2024-01-25 13:31:25.4|Error|run-trimmer.sh|    raise JSONDecodeError("Expecting value", s, err.value) from None
2024-01-25 13:31:25.5|Error|run-trimmer.sh|json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-01-25 13:31:25.5|Debug|CustomScript|Executed external script: /config/CustomScripts/run-trimmer.sh - Status: 1
2024-01-25 13:31:25.5|Debug|CustomScript|Script Output: 
01/25/2024 19:31:25 - Standard - ERROR    404 Not Found
01/25/2024 19:31:25 - Standard - ERROR    b''
01/25/2024 19:31:25 - Error - Traceback (most recent call last):
01/25/2024 19:31:25 - Error -   File "/config/CustomScripts/sonarr-episode-trimmer.py", line 132, in <module>
01/25/2024 19:31:25 - Error -     series = api_request('series')
01/25/2024 19:31:25 - Error -              ^^^^^^^^^^^^^^^^^^^^^
01/25/2024 19:31:25 - Error -   File "/config/CustomScripts/sonarr-episode-trimmer.py", line 47, in api_request
01/25/2024 19:31:25 - Error -     return json.loads(resp_body)
01/25/2024 19:31:25 - Error -            ^^^^^^^^^^^^^^^^^^^^^
01/25/2024 19:31:25 - Error -   File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
01/25/2024 19:31:25 - Error -     return _default_decoder.decode(s)
01/25/2024 19:31:25 - Error -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
01/25/2024 19:31:25 - Error -   File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
01/25/2024 19:31:25 - Error -     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
01/25/2024 19:31:25 - Error -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01/25/2024 19:31:25 - Error -   File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
01/25/2024 19:31:25 - Error -     raise JSONDecodeError("Expecting value", s, err.value) from None
01/25/2024 19:31:25 - Error - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-01-25 13:31:25.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Script exited with code: 1
2024-01-25 13:31:25.5|Debug|Api|[POST] /api/v3/notification/test: 400.BadRequest (385 ms)

**Comment by Ozymandyaz** [comment]
Sonarr updated to their v4 and this changed the API URL slightly. 

Line 35 of the sonarr-episode-trimmer.py needs to be changed to:
`    url = "%s/api/v3/%s?%s" % (url_base, action, urllib.parse.urlencode(params))`
